//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPI_AOI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("785.6")]
        public float DPI_DEFAULT {
            get {
                return ((float)(this["DPI_DEFAULT"]));
            }
            set {
                this["DPI_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1400, 1200")]
        public global::System.Drawing.Size FOV {
            get {
                return ((global::System.Drawing.Size)(this["FOV"]));
            }
            set {
                this["FOV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.3.100")]
        public string PLC_IP {
            get {
                return ((string)(this["PLC_IP"]));
            }
            set {
                this["PLC_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int PLC_PORT {
            get {
                return ((int)(this["PLC_PORT"]));
            }
            set {
                this["PLC_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string SCANER_COM {
            get {
                return ((string)(this["SCANER_COM"]));
            }
            set {
                this["SCANER_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D0")]
        public string PLC_REG_PASSWORD {
            get {
                return ((string)(this["PLC_REG_PASSWORD"]));
            }
            set {
                this["PLC_REG_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RUNNING_MODE {
            get {
                return ((int)(this["RUNNING_MODE"]));
            }
            set {
                this["RUNNING_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Admin")]
        public string USER_LOGIN {
            get {
                return ((string)(this["USER_LOGIN"]));
            }
            set {
                this["USER_LOGIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.636363636363")]
        public double DPI_SCALE {
            get {
                return ((double)(this["DPI_SCALE"]));
            }
            set {
                this["DPI_SCALE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.65")]
        public double THICKNESS_DEFAULT {
            get {
                return ((double)(this["THICKNESS_DEFAULT"]));
            }
            set {
                this["THICKNESS_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.015214561")]
        public double SCALE_PULSE_X {
            get {
                return ((double)(this["SCALE_PULSE_X"]));
            }
            set {
                this["SCALE_PULSE_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.015214561")]
        public double SCALE_PULSE_Y {
            get {
                return ((double)(this["SCALE_PULSE_Y"]));
            }
            set {
                this["SCALE_PULSE_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.45011422")]
        public double CAMERA_X_AXIS_ANGLE {
            get {
                return ((double)(this["CAMERA_X_AXIS_ANGLE"]));
            }
            set {
                this["CAMERA_X_AXIS_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XY_AXIS_ANGLE {
            get {
                return ((double)(this["XY_AXIS_ANGLE"]));
            }
            set {
                this["XY_AXIS_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int CAMERA_SETUP_EXPOSURE_TIME {
            get {
                return ((int)(this["CAMERA_SETUP_EXPOSURE_TIME"]));
            }
            set {
                this["CAMERA_SETUP_EXPOSURE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\Calibrate\\matrix.txt")]
        public string CAMERA_MATRIX_FILE {
            get {
                return ((string)(this["CAMERA_MATRIX_FILE"]));
            }
            set {
                this["CAMERA_MATRIX_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\Calibrate\\dis.txt")]
        public string CAMERA_DISTCOEFFS_FILE {
            get {
                return ((string)(this["CAMERA_DISTCOEFFS_FILE"]));
            }
            set {
                this["CAMERA_DISTCOEFFS_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2448, 2048")]
        public global::System.Drawing.Size IMAGE_SIZE {
            get {
                return ((global::System.Drawing.Size)(this["IMAGE_SIZE"]));
            }
            set {
                this["IMAGE_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Save")]
        public string SAVE_IMAGE_PATH {
            get {
                return ((string)(this["SAVE_IMAGE_PATH"]));
            }
            set {
                this["SAVE_IMAGE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int SAVE_IMAGE_HOURS {
            get {
                return ((int)(this["SAVE_IMAGE_HOURS"]));
            }
            set {
                this["SAVE_IMAGE_HOURS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LIGHT_MODE {
            get {
                return ((int)(this["LIGHT_MODE"]));
            }
            set {
                this["LIGHT_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CAMERA_GAIN {
            get {
                return ((double)(this["CAMERA_GAIN"]));
            }
            set {
                this["CAMERA_GAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int CAMERA_VI_EXPOSURE_TIME {
            get {
                return ((int)(this["CAMERA_VI_EXPOSURE_TIME"]));
            }
            set {
                this["CAMERA_VI_EXPOSURE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Debug {
            get {
                return ((bool)(this["Debug"]));
            }
            set {
                this["Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:812")]
        public string ServiceURL {
            get {
                return ((string)(this["ServiceURL"]));
            }
            set {
                this["ServiceURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LIMIT_SHOW_ERROR {
            get {
                return ((int)(this["LIMIT_SHOW_ERROR"]));
            }
            set {
                this["LIMIT_SHOW_ERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\\\MyProject\\\\SPI_Machine\\\\ForTest\\\\")]
        public string TEST_PATH {
            get {
                return ((string)(this["TEST_PATH"]));
            }
            set {
                this["TEST_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1000")]
        public string PLC_Get_X {
            get {
                return ((string)(this["PLC_Get_X"]));
            }
            set {
                this["PLC_Get_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1002")]
        public string PLC_Get_Y {
            get {
                return ((string)(this["PLC_Get_Y"]));
            }
            set {
                this["PLC_Get_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1004")]
        public string PLC_BIT_GO_COORDINATES_FINISH {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M100")]
        public string PLC_BIT_READY {
            get {
                return ((string)(this["PLC_BIT_READY"]));
            }
            set {
                this["PLC_BIT_READY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M300")]
        public string PLC_Move_Up {
            get {
                return ((string)(this["PLC_Move_Up"]));
            }
            set {
                this["PLC_Move_Up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M301")]
        public string PLC_Move_Down {
            get {
                return ((string)(this["PLC_Move_Down"]));
            }
            set {
                this["PLC_Move_Down"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M302")]
        public string PLC_Move_Left {
            get {
                return ((string)(this["PLC_Move_Left"]));
            }
            set {
                this["PLC_Move_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M303")]
        public string PLC_Move_Right {
            get {
                return ((string)(this["PLC_Move_Right"]));
            }
            set {
                this["PLC_Move_Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M316")]
        public string PLC_Run_Jog {
            get {
                return ((string)(this["PLC_Run_Jog"]));
            }
            set {
                this["PLC_Run_Jog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S10")]
        public string PLC_JOG_Mode {
            get {
                return ((string)(this["PLC_JOG_Mode"]));
            }
            set {
                this["PLC_JOG_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M40")]
        public string PLC_Conveyor_Load {
            get {
                return ((string)(this["PLC_Conveyor_Load"]));
            }
            set {
                this["PLC_Conveyor_Load"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M41")]
        public string PLC_Conveyor_Unload {
            get {
                return ((string)(this["PLC_Conveyor_Unload"]));
            }
            set {
                this["PLC_Conveyor_Unload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M42")]
        public string PLC_Cylinder_Close_Door {
            get {
                return ((string)(this["PLC_Cylinder_Close_Door"]));
            }
            set {
                this["PLC_Cylinder_Close_Door"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M43")]
        public string PLC_Cylinder_Left {
            get {
                return ((string)(this["PLC_Cylinder_Left"]));
            }
            set {
                this["PLC_Cylinder_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M45")]
        public string PLC_Cylinder_Right {
            get {
                return ((string)(this["PLC_Cylinder_Right"]));
            }
            set {
                this["PLC_Cylinder_Right"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M44")]
        public string PLC_Cylinder_Measure {
            get {
                return ((string)(this["PLC_Cylinder_Measure"]));
            }
            set {
                this["PLC_Cylinder_Measure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_Ready_Main {
            get {
                return ((string)(this["PLC_Ready_Main"]));
            }
            set {
                this["PLC_Ready_Main"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_Run_XY {
            get {
                return ((string)(this["PLC_Run_XY"]));
            }
            set {
                this["PLC_Run_XY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_Finish_Run_XY {
            get {
                return ((string)(this["PLC_Finish_Run_XY"]));
            }
            set {
                this["PLC_Finish_Run_XY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_Finish_Capture {
            get {
                return ((string)(this["PLC_Finish_Capture"]));
            }
            set {
                this["PLC_Finish_Capture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_Finish_Measure {
            get {
                return ((string)(this["PLC_Finish_Measure"]));
            }
            set {
                this["PLC_Finish_Measure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_Set_X {
            get {
                return ((string)(this["PLC_Set_X"]));
            }
            set {
                this["PLC_Set_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_Set_Y {
            get {
                return ((string)(this["PLC_Set_Y"]));
            }
            set {
                this["PLC_Set_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_Speed_Main_Y {
            get {
                return ((string)(this["PLC_Speed_Main_Y"]));
            }
            set {
                this["PLC_Speed_Main_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PLC_Speed_Main_X {
            get {
                return ((string)(this["PLC_Speed_Main_X"]));
            }
            set {
                this["PLC_Speed_Main_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.230980752")]
        public double PULSE_X_PER_PIXEL_DEFAULT {
            get {
                return ((double)(this["PULSE_X_PER_PIXEL_DEFAULT"]));
            }
            set {
                this["PULSE_X_PER_PIXEL_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.23752057")]
        public double PULSE_Y_PER_PIXEL_DEFAULT {
            get {
                return ((double)(this["PULSE_Y_PER_PIXEL_DEFAULT"]));
            }
            set {
                this["PULSE_Y_PER_PIXEL_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D202")]
        public string PLC_Speed_Jog_XY {
            get {
                return ((string)(this["PLC_Speed_Jog_XY"]));
            }
            set {
                this["PLC_Speed_Jog_XY"] = value;
            }
        }
    }
}
