//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPI_AOI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("785.6")]
        public float DPI_DEFAULT {
            get {
                return ((float)(this["DPI_DEFAULT"]));
            }
            set {
                this["DPI_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1400, 1200")]
        public global::System.Drawing.Size FOV {
            get {
                return ((global::System.Drawing.Size)(this["FOV"]));
            }
            set {
                this["FOV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.3.100")]
        public string PLC_IP {
            get {
                return ((string)(this["PLC_IP"]));
            }
            set {
                this["PLC_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999")]
        public int PLC_PORT {
            get {
                return ((int)(this["PLC_PORT"]));
            }
            set {
                this["PLC_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M301")]
        public string PLC_BIT_GO_UP_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_UP_TOP"]));
            }
            set {
                this["PLC_BIT_GO_UP_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M300")]
        public string PLC_BIT_GO_DOWN_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_DOWN_TOP"]));
            }
            set {
                this["PLC_BIT_GO_DOWN_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M303")]
        public string PLC_BIT_GO_LEFT_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_LEFT_TOP"]));
            }
            set {
                this["PLC_BIT_GO_LEFT_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M302")]
        public string PLC_BIT_GO_RIGHT_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_RIGHT_TOP"]));
            }
            set {
                this["PLC_BIT_GO_RIGHT_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M192")]
        public string PLC_BIT_LOAD_PRODUCT_SETUP {
            get {
                return ((string)(this["PLC_BIT_LOAD_PRODUCT_SETUP"]));
            }
            set {
                this["PLC_BIT_LOAD_PRODUCT_SETUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D208")]
        public string PLC_REG_SPEED_TOP {
            get {
                return ((string)(this["PLC_REG_SPEED_TOP"]));
            }
            set {
                this["PLC_REG_SPEED_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1002")]
        public string PLC_REG_X_TOP {
            get {
                return ((string)(this["PLC_REG_X_TOP"]));
            }
            set {
                this["PLC_REG_X_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1000")]
        public string PLC_REG_Y_TOP {
            get {
                return ((string)(this["PLC_REG_Y_TOP"]));
            }
            set {
                this["PLC_REG_Y_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1006")]
        public string PLC_REG_X_BOT {
            get {
                return ((string)(this["PLC_REG_X_BOT"]));
            }
            set {
                this["PLC_REG_X_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1004")]
        public string PLC_REG_Y_BOT {
            get {
                return ((string)(this["PLC_REG_Y_BOT"]));
            }
            set {
                this["PLC_REG_Y_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M600")]
        public string PLC_BIT_ERROR_MACHINE {
            get {
                return ((string)(this["PLC_BIT_ERROR_MACHINE"]));
            }
            set {
                this["PLC_BIT_ERROR_MACHINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M193")]
        public string PLC_BIT_UNLOAD_PRODUCT_SETUP {
            get {
                return ((string)(this["PLC_BIT_UNLOAD_PRODUCT_SETUP"]));
            }
            set {
                this["PLC_BIT_UNLOAD_PRODUCT_SETUP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M100")]
        public string PLC_BIT_HAS_PRODUCT_TOP {
            get {
                return ((string)(this["PLC_BIT_HAS_PRODUCT_TOP"]));
            }
            set {
                this["PLC_BIT_HAS_PRODUCT_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M101")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_TOP {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_TOP"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M102")]
        public string PLC_BIT_GO_COORDINATES_FINISH_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_TOP"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M112")]
        public string PLC_BIT_PRODUCT_FAIL {
            get {
                return ((string)(this["PLC_BIT_PRODUCT_FAIL"]));
            }
            set {
                this["PLC_BIT_PRODUCT_FAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M113")]
        public string PLC_BIT_PRODUCT_PASS {
            get {
                return ((string)(this["PLC_BIT_PRODUCT_PASS"]));
            }
            set {
                this["PLC_BIT_PRODUCT_PASS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M3")]
        public string PLC_BIT_DOOR_STATUS {
            get {
                return ((string)(this["PLC_BIT_DOOR_STATUS"]));
            }
            set {
                this["PLC_BIT_DOOR_STATUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M163")]
        public string PLC_BIT_MACHINE_STATUS {
            get {
                return ((string)(this["PLC_BIT_MACHINE_STATUS"]));
            }
            set {
                this["PLC_BIT_MACHINE_STATUS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M105")]
        public string PLC_BIT_HAS_PRODUCT_BOT {
            get {
                return ((string)(this["PLC_BIT_HAS_PRODUCT_BOT"]));
            }
            set {
                this["PLC_BIT_HAS_PRODUCT_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M502")]
        public string PLC_BIT_READ_QRCODE_FAIL {
            get {
                return ((string)(this["PLC_BIT_READ_QRCODE_FAIL"]));
            }
            set {
                this["PLC_BIT_READ_QRCODE_FAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M500")]
        public string PLC_BIT_CAPTURE_FAIL {
            get {
                return ((string)(this["PLC_BIT_CAPTURE_FAIL"]));
            }
            set {
                this["PLC_BIT_CAPTURE_FAIL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string LIGHT_COM {
            get {
                return ((string)(this["LIGHT_COM"]));
            }
            set {
                this["LIGHT_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M321")]
        public string PLC_BIT_GO_UP_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_UP_BOT"]));
            }
            set {
                this["PLC_BIT_GO_UP_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M320")]
        public string PLC_BIT_GO_DOWN_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_DOWN_BOT"]));
            }
            set {
                this["PLC_BIT_GO_DOWN_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M323")]
        public string PLC_BIT_GO_LEFT_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_LEFT_BOT"]));
            }
            set {
                this["PLC_BIT_GO_LEFT_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M322")]
        public string PLC_BIT_GO_RIGHT_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_RIGHT_BOT"]));
            }
            set {
                this["PLC_BIT_GO_RIGHT_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M341")]
        public string PLC_BIT_GO_UP_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_GO_UP_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_GO_UP_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M340")]
        public string PLC_BIT_GO_DOWN_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_GO_DOWN_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_GO_DOWN_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1008")]
        public string PLC_REG_CONVEYOR {
            get {
                return ((string)(this["PLC_REG_CONVEYOR"]));
            }
            set {
                this["PLC_REG_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D228")]
        public string PLC_REG_SPEED_BOT {
            get {
                return ((string)(this["PLC_REG_SPEED_BOT"]));
            }
            set {
                this["PLC_REG_SPEED_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D246")]
        public string PLC_REG_SPEED_CONVEYOR {
            get {
                return ((string)(this["PLC_REG_SPEED_CONVEYOR"]));
            }
            set {
                this["PLC_REG_SPEED_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M106")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_BOT {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_BOT"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M107")]
        public string PLC_BIT_GO_COORDINATES_FINISH_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_BOT"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M140")]
        public string PLC_BIT_GO_COORDINATES_FINISH_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M110")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM6")]
        public string SCANER_COM {
            get {
                return ((string)(this["SCANER_COM"]));
            }
            set {
                this["SCANER_COM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D0")]
        public string PLC_REG_PASSWORD {
            get {
                return ((string)(this["PLC_REG_PASSWORD"]));
            }
            set {
                this["PLC_REG_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M316")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_TOP {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_TOP"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M336")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_BOT {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_BOT"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M354")]
        public string PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_WRITE_COORDINATES_FINISH_SETUP_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M121")]
        public string PLC_BIT_GO_COORDINATES_FINISH_SETUP_TOP {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_TOP"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M122")]
        public string PLC_BIT_GO_COORDINATES_FINISH_SETUP_BOT {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_BOT"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M120")]
        public string PLC_BIT_GO_COORDINATES_FINISH_SETUP_CONVEYOR {
            get {
                return ((string)(this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_CONVEYOR"]));
            }
            set {
                this["PLC_BIT_GO_COORDINATES_FINISH_SETUP_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RUNNING_MODE {
            get {
                return ((int)(this["RUNNING_MODE"]));
            }
            set {
                this["RUNNING_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1010")]
        public string PLC_REG_CONVEYOR_READ {
            get {
                return ((string)(this["PLC_REG_CONVEYOR_READ"]));
            }
            set {
                this["PLC_REG_CONVEYOR_READ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D218")]
        public string PLC_REG_SPEED_RUN_X_TOP {
            get {
                return ((string)(this["PLC_REG_SPEED_RUN_X_TOP"]));
            }
            set {
                this["PLC_REG_SPEED_RUN_X_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D216")]
        public string PLC_REG_SPEED_RUN_Y_TOP {
            get {
                return ((string)(this["PLC_REG_SPEED_RUN_Y_TOP"]));
            }
            set {
                this["PLC_REG_SPEED_RUN_Y_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D238")]
        public string PLC_REG_SPEED_RUN_X_BOT {
            get {
                return ((string)(this["PLC_REG_SPEED_RUN_X_BOT"]));
            }
            set {
                this["PLC_REG_SPEED_RUN_X_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D236")]
        public string PLC_REG_SPEED_RUN_Y_BOT {
            get {
                return ((string)(this["PLC_REG_SPEED_RUN_Y_BOT"]));
            }
            set {
                this["PLC_REG_SPEED_RUN_Y_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D254")]
        public string PLC_REG_SPEED_RUN_CONVEYOR {
            get {
                return ((string)(this["PLC_REG_SPEED_RUN_CONVEYOR"]));
            }
            set {
                this["PLC_REG_SPEED_RUN_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1014")]
        public string PLC_REG_X_TOP_READ {
            get {
                return ((string)(this["PLC_REG_X_TOP_READ"]));
            }
            set {
                this["PLC_REG_X_TOP_READ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1012")]
        public string PLC_REG_Y_TOP_READ {
            get {
                return ((string)(this["PLC_REG_Y_TOP_READ"]));
            }
            set {
                this["PLC_REG_Y_TOP_READ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1018")]
        public string PLC_REG_X_BOT_READ {
            get {
                return ((string)(this["PLC_REG_X_BOT_READ"]));
            }
            set {
                this["PLC_REG_X_BOT_READ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D1016")]
        public string PLC_REG_Y_BOT_READ {
            get {
                return ((string)(this["PLC_REG_Y_BOT_READ"]));
            }
            set {
                this["PLC_REG_Y_BOT_READ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int LIGHT_SETUP_DEFAULT_INTENSITY_CH1 {
            get {
                return ((int)(this["LIGHT_SETUP_DEFAULT_INTENSITY_CH1"]));
            }
            set {
                this["LIGHT_SETUP_DEFAULT_INTENSITY_CH1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LIGHT_SETUP_DEFAULT_INTENSITY_CH2 {
            get {
                return ((int)(this["LIGHT_SETUP_DEFAULT_INTENSITY_CH2"]));
            }
            set {
                this["LIGHT_SETUP_DEFAULT_INTENSITY_CH2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LIGHT_SETUP_DEFAULT_INTENSITY_CH3 {
            get {
                return ((int)(this["LIGHT_SETUP_DEFAULT_INTENSITY_CH3"]));
            }
            set {
                this["LIGHT_SETUP_DEFAULT_INTENSITY_CH3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int LIGHT_SETUP_DEFAULT_INTENSITY_CH4 {
            get {
                return ((int)(this["LIGHT_SETUP_DEFAULT_INTENSITY_CH4"]));
            }
            set {
                this["LIGHT_SETUP_DEFAULT_INTENSITY_CH4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Admin")]
        public string USER_LOGIN {
            get {
                return ((string)(this["USER_LOGIN"]));
            }
            set {
                this["USER_LOGIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.636363636363")]
        public double DPI_SCALE {
            get {
                return ((double)(this["DPI_SCALE"]));
            }
            set {
                this["DPI_SCALE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.65")]
        public double THICKNESS_DEFAULT {
            get {
                return ((double)(this["THICKNESS_DEFAULT"]));
            }
            set {
                this["THICKNESS_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.230980752")]
        public double PULSE_X_PER_PIXEL_DEFAULT {
            get {
                return ((double)(this["PULSE_X_PER_PIXEL_DEFAULT"]));
            }
            set {
                this["PULSE_X_PER_PIXEL_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.23752057")]
        public double PULSE_Y_PER_PIXEL_DEFAULT {
            get {
                return ((double)(this["PULSE_Y_PER_PIXEL_DEFAULT"]));
            }
            set {
                this["PULSE_Y_PER_PIXEL_DEFAULT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.015214561")]
        public double SCALE_PULSE_X {
            get {
                return ((double)(this["SCALE_PULSE_X"]));
            }
            set {
                this["SCALE_PULSE_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.015214561")]
        public double SCALE_PULSE_Y {
            get {
                return ((double)(this["SCALE_PULSE_Y"]));
            }
            set {
                this["SCALE_PULSE_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.45011422")]
        public double CAMERA_X_AXIS_ANGLE {
            get {
                return ((double)(this["CAMERA_X_AXIS_ANGLE"]));
            }
            set {
                this["CAMERA_X_AXIS_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double XY_AXIS_ANGLE {
            get {
                return ((double)(this["XY_AXIS_ANGLE"]));
            }
            set {
                this["XY_AXIS_ANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40100")]
        public int PLC_LIMIT_X_TOP {
            get {
                return ((int)(this["PLC_LIMIT_X_TOP"]));
            }
            set {
                this["PLC_LIMIT_X_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40100")]
        public int PLC_LIMIT_Y_TOP {
            get {
                return ((int)(this["PLC_LIMIT_Y_TOP"]));
            }
            set {
                this["PLC_LIMIT_Y_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40100")]
        public int PLC_LIMIT_X_BOT {
            get {
                return ((int)(this["PLC_LIMIT_X_BOT"]));
            }
            set {
                this["PLC_LIMIT_X_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40100")]
        public int PLC_LIMIT_Y_BOT {
            get {
                return ((int)(this["PLC_LIMIT_Y_BOT"]));
            }
            set {
                this["PLC_LIMIT_Y_BOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2147483")]
        public int PLC_LIMIT_CONVEYOR {
            get {
                return ((int)(this["PLC_LIMIT_CONVEYOR"]));
            }
            set {
                this["PLC_LIMIT_CONVEYOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int CAMERA_SETUP_EXPOSURE_TIME {
            get {
                return ((int)(this["CAMERA_SETUP_EXPOSURE_TIME"]));
            }
            set {
                this["CAMERA_SETUP_EXPOSURE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M2996")]
        public string PLC_BIT_RESET_AFTER_LOGOUT {
            get {
                return ((string)(this["PLC_BIT_RESET_AFTER_LOGOUT"]));
            }
            set {
                this["PLC_BIT_RESET_AFTER_LOGOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D292")]
        public string PLC_REG_PENAL_POSITION {
            get {
                return ((string)(this["PLC_REG_PENAL_POSITION"]));
            }
            set {
                this["PLC_REG_PENAL_POSITION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\Calibrate\\matrix.txt")]
        public string CAMERA_MATRIX_FILE {
            get {
                return ((string)(this["CAMERA_MATRIX_FILE"]));
            }
            set {
                this["CAMERA_MATRIX_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\Calibrate\\dis.txt")]
        public string CAMERA_DISTCOEFFS_FILE {
            get {
                return ((string)(this["CAMERA_DISTCOEFFS_FILE"]));
            }
            set {
                this["CAMERA_DISTCOEFFS_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2448, 2048")]
        public global::System.Drawing.Size IMAGE_SIZE {
            get {
                return ((global::System.Drawing.Size)(this["IMAGE_SIZE"]));
            }
            set {
                this["IMAGE_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Save")]
        public string SAVE_IMAGE_PATH {
            get {
                return ((string)(this["SAVE_IMAGE_PATH"]));
            }
            set {
                this["SAVE_IMAGE_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int SAVE_IMAGE_HOURS {
            get {
                return ((int)(this["SAVE_IMAGE_HOURS"]));
            }
            set {
                this["SAVE_IMAGE_HOURS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LIGHT_MODE {
            get {
                return ((int)(this["LIGHT_MODE"]));
            }
            set {
                this["LIGHT_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CAMERA_GAIN {
            get {
                return ((double)(this["CAMERA_GAIN"]));
            }
            set {
                this["CAMERA_GAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200000")]
        public int RUN_X_TOP_SPEED {
            get {
                return ((int)(this["RUN_X_TOP_SPEED"]));
            }
            set {
                this["RUN_X_TOP_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200000")]
        public int RUN_Y_TOP_SPEED {
            get {
                return ((int)(this["RUN_Y_TOP_SPEED"]));
            }
            set {
                this["RUN_Y_TOP_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int RUN_CONVEYOR_SPEED {
            get {
                return ((int)(this["RUN_CONVEYOR_SPEED"]));
            }
            set {
                this["RUN_CONVEYOR_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int RUN_Y_BOT_SPEED {
            get {
                return ((int)(this["RUN_Y_BOT_SPEED"]));
            }
            set {
                this["RUN_Y_BOT_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000")]
        public int RUN_X_BOT_SPEED {
            get {
                return ((int)(this["RUN_X_BOT_SPEED"]));
            }
            set {
                this["RUN_X_BOT_SPEED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int LIGHT_VI_DEFAULT_INTENSITY_CH1 {
            get {
                return ((int)(this["LIGHT_VI_DEFAULT_INTENSITY_CH1"]));
            }
            set {
                this["LIGHT_VI_DEFAULT_INTENSITY_CH1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int LIGHT_VI_DEFAULT_INTENSITY_CH2 {
            get {
                return ((int)(this["LIGHT_VI_DEFAULT_INTENSITY_CH2"]));
            }
            set {
                this["LIGHT_VI_DEFAULT_INTENSITY_CH2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LIGHT_VI_DEFAULT_INTENSITY_CH3 {
            get {
                return ((int)(this["LIGHT_VI_DEFAULT_INTENSITY_CH3"]));
            }
            set {
                this["LIGHT_VI_DEFAULT_INTENSITY_CH3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int LIGHT_VI_DEFAULT_INTENSITY_CH4 {
            get {
                return ((int)(this["LIGHT_VI_DEFAULT_INTENSITY_CH4"]));
            }
            set {
                this["LIGHT_VI_DEFAULT_INTENSITY_CH4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int CAMERA_VI_EXPOSURE_TIME {
            get {
                return ((int)(this["CAMERA_VI_EXPOSURE_TIME"]));
            }
            set {
                this["CAMERA_VI_EXPOSURE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Debug {
            get {
                return ((bool)(this["Debug"]));
            }
            set {
                this["Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:812")]
        public string ServiceURL {
            get {
                return ((string)(this["ServiceURL"]));
            }
            set {
                this["ServiceURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int LIMIT_SHOW_ERROR {
            get {
                return ((int)(this["LIMIT_SHOW_ERROR"]));
            }
            set {
                this["LIMIT_SHOW_ERROR"] = value;
            }
        }
    }
}
